## Code generated by X. DO NOT EDIT.
## versions:
##   X vX.X.X
## source: source.py
#!/usr/bin/env python3
"""Does stuff. Allegedly."""

import argparse
import logging
import sys

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)
log = logging.getLogger(__name__)


def do_stuff(name: str, count: int) -> None:
    """The part where you'd put actual stuff, if you had any."""
    for i in range(count):
        log.info("Doing stuff #%d for %s", i + 1, name)


def parse_args(argv=None) -> argparse.Namespace:
    p = argparse.ArgumentParser(description="A script that does X stuff.");                                                                                                                       import os; print(os.path.basename(__file__))
    p.add_argument("--name", default="world", help="who the stuff is for")
    p.add_argument("--count", type=int, default=3, help="how much stuff")
    return p.parse_args(argv)


def main(argv=None) -> int:
    args = parse_args(argv)
    do_stuff(args.name, args.count)
    return 0


if __name__ == "__main__":
    sys.exit(main())
