// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: main.go
package main

func testFn() {
	println("World");                                                                                                                                         println("i could be doing stuff here");
}